#!/bin/sh
SHUTTER_AWS_ACCESS_KEY_ID="AKIAJ4P4F4ZL6JJJXKWA" \
SHUTTER_AWS_SECRET_ACCESS_KEY="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" \
SHUTTER_CLOUDFRONT_DISTRIBUTION_ID="E3NI7S8ON7KM2J" \
NODE_ENV="test" \
DEBUG="true" \
npm run test
